### ISSUE TITLE
Traffic doesn't go through wireguard

### ISSUE THREAD

**Issue by pierremedard** [hongwenjun/WinKcp_Launcher#2]
I've been trying to use WinKcp_Launcher following the youtube tutorial but it seems like the traffic is not being redirected correctly by wireguard.

I tried to use the software directly but it didn't seem to work so i launched udp2raw and speedserv2 manually, i managed to connect wireguard, but nothing is going through:

![issue](https://user-images.githubusercontent.com/29196952/60858112-9badaa80-a23f-11e9-95dc-176b012981ab.png)

![ping](https://user-images.githubusercontent.com/29196952/60858122-a7996c80-a23f-11e9-8452-bbf94229b702.png)

Everything seems to be connected but the traffic just won't be redirected for some reason, do you have any ideas? Thanks

**Comment by hongwenjun** [comment]
https://github.com/hongwenjun/WinKcp_Launcher/tree/master/template

### /etc/rc.local
```
# WG + Speeder + Udp2RAW   ....  Fragment
speederv2 -s -l127.0.0.1:8888  -r127.0.0.1:8000  -f20:10 -k wg2999 --mode 0  >> /var/log/speederv2.log &
udp2raw   -s -l0.0.0.0:2999  -r 127.0.0.1:8888  -k wg2999 --raw-mode faketcp  >> /var/log/wg_udp2raw.log &

```

![](https://raw.githubusercontent.com/hongwenjun/vps_setup/master/img/speed_udp2raw_debug.png)
### Windows_UDP2RAW.cmd
```
@echo.
@set PATH=%~dp0;%PATH%

@set SERVER_IP=118.24.232.233
@set PORT=2999
@set PASSWORD=wg2999
@set WG_PORT=8000

@set GATEWAY=192.168.1.1
@route DELETE %SERVER_IP%  && route ADD %SERVER_IP% mask 255.255.255.255 %GATEWAY% METRIC 20
@start /b udp2raw -c -r%SERVER_IP%:%PORT% -l0.0.0.0:8888 -k %PASSWORD% --raw-mode faketcp
@start /b speederv2  -c -l0.0.0.0:%WG_PORT% -r127.0.0.1:8888 -f20:10 -k %PASSWORD% --mode 0
```

**Comment by hongwenjun** [comment]
> I've been trying to use WinKcp_Launcher following the youtube tutorial but it seems like the traffic is not being redirected correctly by wireguard.
> 
> I tried to use the software directly but it didn't seem to work so i launched udp2raw and speedserv2 manually, i managed to connect wireguard, but nothing is going through:
> 
> ![issue](https://user-images.githubusercontent.com/29196952/60858112-9badaa80-a23f-11e9-95dc-176b012981ab.png)
> 
> ![ping](https://user-images.githubusercontent.com/29196952/60858122-a7996c80-a23f-11e9-8452-bbf94229b702.png)
> 
> Everything seems to be connected but the traffic just won't be redirected for some reason, do you have any ideas? Thanks

-l0.0.0.0:8888     L not One ( l not 1)

**Comment by pierremedard** [comment]
Sorry for the late reply, i'm using l not 1. My screen isn't clear but it's an "l", i don't see any difference, it seems like i'm connected to my VULTR server and my wg is also connected with TunSafe, it looks like everything is working but just no traffic forwarding

**Comment by hongwenjun** [comment]
参考 https://github.com/hongwenjun/WinKcp_Launcher/tree/master/template

**Comment by pierremedard** [comment]
I did exactly like in the template, udp2speed works fine, udpraw works too, wireguard is connected but i get this error in wg:
![wg_log](https://user-images.githubusercontent.com/29196952/60902761-bcf3b280-a2a2-11e9-99f5-c06c62ff6d7d.png)

I was thinking maybe my vultr was block by the GFW, but i don't think so because UDP2RAW and udpspeeder works!
![udp](https://user-images.githubusercontent.com/29196952/60902881-ef051480-a2a2-11e9-9371-b0ca8c7d64e8.png)

I did EVERYTHING like in the tutorial :/

**Comment by hongwenjun** [comment]
> Sorry for the late reply, i'm using l not 1. My screen isn't clear but it's an "l", i don't see any difference, it seems like i'm connected to my VULTR server and my wg is also connected with TunSafe, it looks like everything is working but just no traffic forwarding

Part :1 WireGuard+Speeder+Udp2Raw and SS+Kcp+Udp2RAW Automated Configuration

https://youtu.be/oGAviPyfWnY
